### ISSUE TITLE
A lot of warnings when running the tests

### ISSUE THREAD

**Issue by diminish7** [diminish7/rave#27]
I get a lot of "already initialized constant" warnings when running the tests. I think because the example bot tests reload the environment. But we should add a check to make sure a constant isn't already defined before defining it

**Comment by bil-bas** [comment]
It is fine in my version, but you are working a bit behind so that bug was still there.

**Comment by bil-bas** [comment]
Actually, this is more correct (standard in any Ruby I've ever seen):

`$:.unshift File.dirname(File.dirname(__FILE__))`

`require 'robot'`

rather than:

`require File.join(File.dirname(__FILE__), '..', 'robot')`

The reason being that you should only require files by name, not path (the former code adds the path into the search). This avoids the possibility of re-requiring the same file.

And that was not the cause of this bug. The actual cause was trying to run the example spec files from the standard 'rake spec', rather than just in rake spooner-test:spec (or directly in the example directories). I took this out of the rakefile and it was fine again for me.

**Comment by bil-bas** [comment]
fixed errors anyway.
